name: create new repository to php candidate
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the repository to be created(use php_challenge_CANDIDATE_GITHUB_USERNAME)'
        required: true
      username:
        description: 'Candidate github username'
        required: true
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create new repository to php candidate
    steps:
      - name: Creating GitHub Organization Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -o bin/repo-generator

      - name: RUN
        id: run
        run: bin/repo-generator

        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          #          ORG_NAME: 'code-with-auto1'
          ORG_NAME: 'yuseferi-test-org'
          NEW_REPO_NAME: '${{ github.event.inputs.repo-name }}'
          GITHUB_USERNAME: '${{ github.event.inputs.username }}'

      - name: "Repo created successfully and the candidate has been invited log"
        run: echo "New Repository created ${{ steps.run.outputs.repo_url }} and ${{ github.event.inputs.username }} has been invited to it."
