name: create new repository to php candidate
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the repository to be created(use php_challenge_CANDIDATE_GITHUB_USERNAME)'
        required: true
      username:
        description: 'Candidate github username'
        required: true
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create new repository to php candidate
    steps:
      - name: Creating GitHub Organization Repository
        uses: golang:1.18-alpine
        id: create-repo
        run: |
          go mod install
          go build -o bin/repo-generator
          bin/repo-generator
        env:
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
#          ORG_NAME: 'code-with-auto1'
          ORG_NAME: 'yuseferi-test-org'
          newRepoName: '${{ github.event.inputs.repo-name }}'
          githubUsername: '${{ github.event.inputs.username }}'
#      - name: Log URL to the repo
#        run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"
